"""
Professional video export service for creating Premiere Pro and DaVinci Resolve projects.

Features:
- Premiere Pro project generation (.prproj)
- DaVinci Resolve project generation (.drp)
- Professional workflow integration
- Metadata preservation
- Media organization
- Quality optimization for professional use
"""

import asyncio
import logging
import os
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Union
from dataclasses import dataclass, field
from enum import Enum
import json
import sqlite3
import time
import uuid
from concurrent.futures import ThreadPoolExecutor

from src.core.schemas.base import BaseNodeInput, BaseNodeOutput
from src.core.replay.manifest import ReplayManifest


class ProjectType(Enum):
    """Supported project types"""
    PREMIERE_PRO = "premiere_pro"
    DAVINCI_RESOLVE = "davinci_resolve"


class ExportFormat(Enum):
    """Export format types"""
    PROJECT = "project"
    SEQUENCE = "sequence"
    TIMELINE = "timeline"


@dataclass
class TimelineData:
    """Timeline data structure"""
    duration: float
    resolution: str
    fps: float
    tracks: List[Dict] = field(default_factory=list)
    markers: List[Dict] = field(default_factory=list)
    metadata: Dict[str, any] = field(default_factory=dict)


@dataclass
class ClipData:
    """Clip data structure"""
    id: str
    name: str
    source_path: str
    start_time: float
    end_time: float
    in_point: float
    out_point: float
    track: int
    effects: List[Dict] = field(default_factory=list)
    metadata: Dict[str, any] = field(default_factory=dict)


@dataclass
class ProjectSettings:
    """Professional export settings"""
    project_type: ProjectType
    export_format: ExportFormat
    include_media: bool = True
    preserve_metadata: bool = True
    optimize_for_professional: bool = True
    custom_template: Optional[str] = None
    workspace_path: Optional[str] = None


@dataclass
class ProjectResult:
    """Professional export result"""
    success: bool
    project_path: str
    project_type: ProjectType
    media_files: List[str]
    processing_time: float
    error_message: Optional[str] = None
    metadata: Dict[str, any] = field(default_factory=dict)


class ProfessionalExporter:
    """
    Professional video export service.

    Creates professional video editing project files
    for Premiere Pro and DaVinci Resolve.
    """

    def __init__(self):
        self.logger = logging.getLogger(__name__)
        self.active_exports: Dict[str, dict] = {}
        self.executor = ThreadPoolExecutor(max_workers=2)

    def _generate_premiere_pro_project(self, timeline_data: TimelineData,
                                     clips: List[ClipData], output_path: str,
                                     settings: ProjectSettings) -> ProjectResult:
        """Generate Premiere Pro project file"""
        try:
            start_time = time.time()

            # Create project structure
            project_root = ET.Element("PremiereData")
            project_root.set("Version", "12.0")

            # Add project metadata
            project_meta = ET.SubElement(project_root, "ProjectMeta")
            ET.SubElement(project_meta, "Name").text = "AI Video Editor Export"
            ET.SubElement(project_meta, "Description").text = "Generated by AI Video Editor"

            # Create sequence
            sequence = ET.SubElement(project_root, "Sequence")
            ET.SubElement(sequence, "Name").text = "Main Sequence"
            ET.SubElement(sequence, "Duration").text = str(int(timeline_data.duration * 30))  # Frame count

            # Add video tracks
            for track_id in range(max(len(clips), 2)):  # At least 2 tracks
                track = ET.SubElement(sequence, "VideoTrack")
                ET.SubElement(track, "TrackID").text = str(track_id)

                # Add clips to track
                track_clips = [clip for clip in clips if clip.track == track_id]
                for clip in track_clips:
                    clip_element = ET.SubElement(track, "Clip")
                    ET.SubElement(clip_element, "Name").text = clip.name
                    ET.SubElement(clip_element, "StartFrame").text = str(int(clip.start_time * 30))
                    ET.SubElement(clip_element, "EndFrame").text = str(int(clip.end_time * 30))
                    ET.SubElement(clip_element, "MediaPath").text = clip.source_path

            # Add audio tracks
            for track_id in range(2):  # Stereo audio
                track = ET.SubElement(sequence, "AudioTrack")
                ET.SubElement(track, "TrackID").text = str(track_id)

            # Write project file
            tree = ET.ElementTree(project_root)
            tree.write(output_path, encoding='utf-8', xml_declaration=True)

            processing_time = time.time() - start_time

            return ProjectResult(
                success=True,
                project_path=output_path,
                project_type=ProjectType.PREMIERE_PRO,
                media_files=[clip.source_path for clip in clips],
                processing_time=processing_time,
                metadata={
                    'clips_count': len(clips),
                    'duration': timeline_data.duration,
                    'resolution': timeline_data.resolution
                }
            )

        except Exception as e:
            return ProjectResult(
                success=False,
                project_path=output_path,
                project_type=ProjectType.PREMIERE_PRO,
                media_files=[],
                processing_time=time.time() - start_time,
                error_message=str(e)
            )

    def _generate_davinci_resolve_project(self, timeline_data: TimelineData,
                                        clips: List[ClipData], output_path: str,
                                        settings: ProjectSettings) -> ProjectResult:
        """Generate DaVinci Resolve project file"""
        try:
            start_time = time.time()

            # Create Resolve project database structure
            # This is a simplified implementation - real Resolve projects are complex SQLite databases

            # Create basic project structure
            project_data = {
                "project": {
                    "name": "AI Video Editor Export",
                    "version": "18.0",
                    "timeline": {
                        "name": "Main Timeline",
                        "duration": timeline_data.duration,
                        "fps": timeline_data.fps,
                        "resolution": timeline_data.resolution,
                        "tracks": {}
                    }
                },
                "clips": {},
                "media": {}
            }

            # Add clips to project
            for clip in clips:
                clip_data = {
                    "id": clip.id,
                    "name": clip.name,
                    "source_path": clip.source_path,
                    "start_time": clip.start_time,
                    "end_time": clip.end_time,
                    "in_point": clip.in_point,
                    "out_point": clip.out_point,
                    "track": clip.track,
                    "metadata": clip.metadata
                }
                project_data["clips"][clip.id] = clip_data

                # Add media reference
                project_data["media"][clip.source_path] = {
                    "type": "video",
                    "duration": clip.end_time - clip.start_time,
                    "resolution": timeline_data.resolution
                }

            # Add tracks
            for track_id in range(max(len(clips), 2)):
                project_data["project"]["timeline"]["tracks"][f"video_{track_id}"] = {
                    "type": "video",
                    "clips": [clip.id for clip in clips if clip.track == track_id]
                }

            # Write project file as JSON (simplified format)
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(project_data, f, indent=2, ensure_ascii=False)

            processing_time = time.time() - start_time

            return ProjectResult(
                success=True,
                project_path=output_path,
                project_type=ProjectType.DAVINCI_RESOLVE,
                media_files=[clip.source_path for clip in clips],
                processing_time=processing_time,
                metadata={
                    'clips_count': len(clips),
                    'duration': timeline_data.duration,
                    'resolution': timeline_data.resolution
                }
            )

        except Exception as e:
            return ProjectResult(
                success=False,
                project_path=output_path,
                project_type=ProjectType.DAVINCI_RESOLVE,
                media_files=[],
                processing_time=time.time() - start_time,
                error_message=str(e)
            )

    def _create_project_directory_structure(self, base_path: str, settings: ProjectSettings) -> str:
        """Create professional project directory structure"""
        project_path = Path(base_path)
        project_path.mkdir(parents=True, exist_ok=True)

        # Create standard professional project structure
        directories = [
            "Media",
            "Sequences",
            "Exports",
            "Cache",
            "Metadata"
        ]

        for dir_name in directories:
            (project_path / dir_name).mkdir(exist_ok=True)

        return str(project_path)

    def _run_professional_export(self, timeline_data: TimelineData,
                               clips: List[ClipData], output_path: str,
                               settings: ProjectSettings) -> ProjectResult:
        """Run professional export"""
        try:
            # Create project directory structure
            project_root = self._create_project_directory_structure(
                os.path.dirname(output_path), settings
            )

            # Generate project based on type
            if settings.project_type == ProjectType.PREMIERE_PRO:
                return self._generate_premiere_pro_project(
                    timeline_data, clips, output_path, settings
                )
            elif settings.project_type == ProjectType.DAVINCI_RESOLVE:
                return self._generate_davinci_resolve_project(
                    timeline_data, clips, output_path, settings
                )
            else:
                raise ValueError(f"Unsupported project type: {settings.project_type}")

        except Exception as e:
            return ProjectResult(
                success=False,
                project_path=output_path,
                project_type=settings.project_type,
                media_files=[],
                processing_time=0,
                error_message=str(e)
            )

    async def export_professional_project(self, timeline_data: TimelineData,
                                        clips: List[ClipData], output_path: str,
                                        settings: ProjectSettings) -> ProjectResult:
        """Export professional project asynchronously"""
        loop = asyncio.get_event_loop()

        # Run export in thread pool
        result = await loop.run_in_executor(
            self.executor,
            self._run_professional_export,
            timeline_data,
            clips,
            output_path,
            settings
        )

        return result

    def get_supported_project_types(self) -> List[Dict]:
        """Get list of supported project types"""
        return [
            {
                'type': ProjectType.PREMIERE_PRO.value,
                'name': 'Adobe Premiere Pro',
                'description': 'Professional video editing software',
                'extensions': ['.prproj'],
                'features': ['Multi-track editing', 'Advanced effects', 'Color correction']
            },
            {
                'type': ProjectType.DAVINCI_RESOLVE.value,
                'name': 'DaVinci Resolve',
                'description': 'Professional color grading and editing',
                'extensions': ['.drp'],
                'features': ['Advanced color grading', 'Fairlight audio', 'Fusion effects']
            }
        ]

    def validate_project_data(self, timeline_data: TimelineData, clips: List[ClipData]) -> List[str]:
        """Validate project data"""
        errors = []

        # Validate timeline data
        if timeline_data.duration <= 0:
            errors.append("Timeline duration must be positive")

        if not timeline_data.resolution:
            errors.append("Timeline resolution is required")

        try:
            width, height = timeline_data.resolution.split('x')
            int(width), int(height)
        except:
            errors.append("Invalid resolution format (use WIDTHxHEIGHT)")

        # Validate clips
        if not clips:
            errors.append("At least one clip is required")

        for clip in clips:
            if clip.start_time >= clip.end_time:
                errors.append(f"Invalid clip timing for {clip.name}")

            if not clip.source_path:
                errors.append(f"Missing source path for {clip.name}")

        return errors

    def estimate_export_time(self, timeline_data: TimelineData, clips: List[ClipData],
                           settings: ProjectSettings) -> float:
        """Estimate professional export time"""
        # Base time estimate
        base_time = len(clips) * 0.1  # 100ms per clip

        # Adjust for project type
        if settings.project_type == ProjectType.PREMIERE_PRO:
            base_time *= 1.5  # Premiere projects are more complex
        elif settings.project_type == ProjectType.DAVINCI_RESOLVE:
            base_time *= 1.2  # Resolve projects are moderately complex

        # Adjust for media inclusion
        if settings.include_media:
            base_time *= 1.3  # Media organization takes time

        # Adjust for metadata preservation
        if settings.preserve_metadata:
            base_time *= 1.2  # Metadata processing takes time

        return max(base_time, 1.0)  # Minimum 1 second

    def cleanup(self):
        """Cleanup resources"""
        self.executor.shutdown(wait=True)
        self.logger.info("ProfessionalExporter cleanup completed")


# Convenience functions for common professional exports
def export_premiere_pro_project(timeline_data: TimelineData, clips: List[ClipData],
                              output_path: str) -> ProjectResult:
    """Export Premiere Pro project"""
    exporter = ProfessionalExporter()
    settings = ProjectSettings(
        project_type=ProjectType.PREMIERE_PRO,
        export_format=ExportFormat.PROJECT
    )

    return asyncio.run(exporter.export_professional_project(
        timeline_data, clips, output_path, settings
    ))


def export_davinci_resolve_project(timeline_data: TimelineData, clips: List[ClipData],
                                 output_path: str) -> ProjectResult:
    """Export DaVinci Resolve project"""
    exporter = ProfessionalExporter()
    settings = ProjectSettings(
        project_type=ProjectType.DAVINCI_RESOLVE,
        export_format=ExportFormat.PROJECT
    )

    return asyncio.run(exporter.export_professional_project(
        timeline_data, clips, output_path, settings
    ))


def create_professional_project_from_timeline(timeline_data: TimelineData,
                                            clips: List[ClipData],
                                            project_type: str = "premiere_pro") -> ProjectResult:
    """Create professional project from timeline data"""
    exporter = ProfessionalExporter()
    settings = ProjectSettings(
        project_type=ProjectType(project_type),
        export_format=ExportFormat.PROJECT
    )

    # Generate output path
    timestamp = int(time.time())
    output_path = f"export_{timestamp}.{ProjectType(project_type).value}.xml"

    return asyncio.run(exporter.export_professional_project(
        timeline_data, clips, output_path, settings
    ))